esphome:
  name: wled-receiver
  friendly_name: WLED Receiver

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable WiFi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Enable fallback access point
  ap:
    ssid: "WLED Receiver Fallback"
    password: !secret fallback_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

# Load the ESP32 WLED Adapter external component
external_components:
  - source: github://AndresDuran53/esp32_wled_adapter@main
    components: [esp32_wled_adapter]

# Define an addressable LED strip (Example with WS2812B)
light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: GPIO2
    num_leds: 60
    name: "LED Strip"
    id: led_strip

# Configure the ESP32 WLED Adapter component
esp32_wled_adapter:
  port: 21324  # Standard WLED UDP port
  light_id: led_strip
