esphome:
  name: wled-receiver
  friendly_name: WLED Receiver

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable WiFi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Enable fallback access point
  ap:
    ssid: "WLED Receiver Fallback"
    password: !secret fallback_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  - platform: esphome
    password: !secret ota_password

# Load the ESP32 WLED Adapter external component
external_components:
  source:
    type: git
    url: https://github.com/AndresDuran53/esp32_wled_adapter

# Configure the ESP32 WLED Adapter component
esp32_wled_adapter:
  port: 21324  # Standard WLED UDP port
  light_id: led_strip

# Define an addressable LED strip (Example with WS2812B)
light:
  - platform: esp32_rmt_led_strip
    id: led_strip
    name: "Strip Lights"
    chipset: ws2811
    pin: GPIO47
    num_leds: 61
    rgb_order: GRB
